Fixed an issue where ALMA running on CPU caused AutoGPTQ to throw an "Exllama" error:
ValueError: Found modules on cpu/disk. Using Exllama or Exllamav2 backend requires all the modules to be on GPU.

https://github.com/huggingface/transformers/blob/main/docs/source/en/quantization.md#exllama